### ISSUE TITLE
Aurora PostgreSQL v11 support

### ISSUE THREAD

**Issue by dylanrathbone** [aws-quickstart/quickstart-amazon-aurora-postgresql#33]
We are currently working on upgrading the Atlassian QuickStart templates so that the version of Aurora PostgreSQL can be selected by the user. As well as being able to select between `v9` and `v10`, It would also be nice if these templates supported `v11`. Is this something that can be added? 

Supported Aurora PostgreSQL versions [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Updates.20180305.html)

**Comment by stieler-it** [comment]
Fixed with https://github.com/aws-quickstart/quickstart-amazon-aurora-postgresql/pull/34 ?
