### ISSUE TITLE
Consider removing EngineVersion from the DB Instances in the Aurora Cluster

### ISSUE THREAD

**Issue by nagraham** [aws-quickstart/quickstart-amazon-aurora-postgresql#46]
https://github.com/aws-quickstart/quickstart-amazon-aurora-postgresql/blob/3748afb2df183c2a81f2be80ca1203e0e9cd2c12/templates/aurora_postgres.template.yaml#L369

This field is unnecessary for instances in an Aurora cluster: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-engineversion.

> Amazon Aurora
> Not applicable. The version number of the database engine to be used by the DB instance is managed by the DB cluster.

This will work when creating the stack, but if you attempt to update the cluster/instances, then the cloudformation deployment will fail with the following error:

> The specified DB Instance is a member of a cluster. Modify the DB engine version for the DB Cluster using the ModifyDbCluster API

**Comment by tonynv** [comment]
Closing not validated. Please PR if still valid
