### ISSUE TITLE
How to deploy with AWS CLI package+deploy

### ISSUE THREAD

**Issue by YSUN-coder** [aws-quickstart/quickstart-amazon-aurora-postgresql#48]
I am working on doing this automation through the local template and upload the templates with its submodule templates to my own S3 bucket, like what `taskcat test run` do. 
Could you add more instruction about how to deploy this Aurora PostgreSQL using AWS CLI, such as` aws cloudformation package` + `aws cloudformation deploy`?
Thanks.

**Comment by tonynv** [comment]
Unclear. Please provide addition detail on your request (if it’s still needed)
