### ISSUE TITLE
Is there an existing automation template for this Aurora's Proxy?

### ISSUE THREAD

**Issue by YSUN-coder** [aws-quickstart/quickstart-amazon-aurora-postgresql#50]
I tried to add both read-write and read instances as the proxy target. But it shows a lack of the read-only endpoint. Is there an existing automation template for this Aurora's Proxy? Or how could we add the automation for Aurora Proxy into the Aurora template?

Thanks.

**Comment by tonynv** [comment]
You can fork the template and make modifications as needed
