### ISSUE TITLE
Versions supported in these templates are old compared to what is available and supported

### ISSUE THREAD

**Issue by aelsnzhvr** [aws-quickstart/quickstart-amazon-aurora-postgresql#52]
When using other QuickStart templates they fail if using this template as submodule. The reason is this template does not include up-to-date supported Aurora PostgreSQL versions.  Example the latest supported version is 12.4 but currently 13.6 is already out.  Also number of the versions listed in this template does not exist anymore which cause other templates to fail if they use this one.
Is it possible to please update to allow latest supported versions?

**Comment by tonynv** [comment]
Happy to review PR with updates
